FROM centos/nginx-116-centos7:1.16

# Add application sources
COPY docker/nginx/nginx.conf "${NGINX_CONF_PATH}"

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"